<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking | Admin Event Organizer</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-[100dvh] bg-[#fff9f3] text-[#2c221e] antialiased"><div class="min-h-[100dvh]">
    @include('components.admin-sidebar')
    <main class="admin-shell-content min-w-0 lg:ml-[248px] lg:max-h-[100dvh] lg:overflow-y-auto"><div class="mx-auto max-w-[1400px] px-5 py-6 sm:px-7 lg:px-12 lg:py-9">
        <header class="border-b border-[#eadfd6] pb-7"><p class="font-mono text-[11px] font-semibold uppercase tracking-[.18em] text-[#f4511e]">Workspace / booking</p><div class="mt-2 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="font-['Outfit'] text-4xl font-extrabold tracking-[-.055em] sm:text-5xl">Booking</h1><p class="mt-3 max-w-[65ch] text-sm leading-6 text-[#756861]">Pantau pembayaran dan status booking tanpa mengubah nilai transaksi.</p></div><span class="border-l-2 border-[#f4511e] pl-4 text-sm text-[#756861]">Admin event · read-only finansial</span></div></header>
        <section class="grid gap-3 py-7 sm:grid-cols-2 lg:grid-cols-5" aria-label="Ringkasan booking"><div class="border-y border-[#eadfd6] bg-white px-4 py-3"><p class="text-[10px] uppercase tracking-[.12em] text-[#756861]">Total booking</p><p class="mt-1 font-['Outfit'] text-2xl font-bold">128</p></div><div class="border-y border-[#eadfd6] bg-white px-4 py-3"><p class="text-[10px] uppercase tracking-[.12em] text-[#756861]">Paid</p><p class="mt-1 font-['Outfit'] text-2xl font-bold text-[#287a54]">94</p></div><div class="border-y border-[#eadfd6] bg-white px-4 py-3"><p class="text-[10px] uppercase tracking-[.12em] text-[#756861]">Pending payment</p><p class="mt-1 font-['Outfit'] text-2xl font-bold text-[#956400]">22</p></div><div class="border-y border-[#eadfd6] bg-white px-4 py-3"><p class="text-[10px] uppercase tracking-[.12em] text-[#756861]">Cancelled</p><p class="mt-1 font-['Outfit'] text-2xl font-bold text-[#b33d38]">12</p></div><div class="border-y border-[#eadfd6] bg-white px-4 py-3 sm:col-span-2 lg:col-span-1"><p class="text-[10px] uppercase tracking-[.12em] text-[#756861]">Total revenue</p><p class="mt-1 font-['Outfit'] text-2xl font-bold">Rp42,8jt</p></div></section>
        <section aria-label="Filter booking" class="border-y border-[#eadfd6] py-5"><form method="GET" action="{{ route('admin.bookings') }}" class="grid gap-3 lg:grid-cols-[minmax(0,1fr)_180px_180px_180px_auto]"><div><label class="sr-only" for="booking-search">Cari booking</label><input id="booking-search" name="q" value="{{ $query ?? '' }}" type="search" placeholder="Kode, pembeli, email, event" class="min-h-11 w-full rounded-[5px] border border-[#eadfd6] bg-white px-4 text-sm focus:border-[#f4511e] focus:ring-0"></div><div><label class="sr-only" for="booking-event">Event</label><select id="booking-event" name="event" class="min-h-11 w-full rounded-[5px] border border-[#eadfd6] bg-white px-3 text-sm focus:border-[#f4511e] focus:ring-0"><option value="">Semua event</option><option>Otaku Matsuri 2026</option><option>Comic Frontier Mini</option></select></div><div><label class="sr-only" for="booking-payment">Status pembayaran</label><select id="booking-payment" name="payment" class="min-h-11 w-full rounded-[5px] border border-[#eadfd6] bg-white px-3 text-sm focus:border-[#f4511e] focus:ring-0"><option value="">Pembayaran</option><option>Paid</option><option>Pending</option></select></div><div><label class="sr-only" for="booking-status">Status booking</label><select id="booking-status" name="status" class="min-h-11 w-full rounded-[5px] border border-[#eadfd6] bg-white px-3 text-sm focus:border-[#f4511e] focus:ring-0"><option value="">Status booking</option><option>Confirmed</option><option>Pending</option><option>Cancelled</option></select></div><button type="submit" class="min-h-11 rounded-[5px] bg-[#f4511e] px-5 text-sm font-bold text-[#fff9f3] hover:bg-[#d94216]">Cari</button></form></section>
        <section class="mt-7" aria-labelledby="booking-list-title"><div class="mb-4 flex items-end justify-between gap-4"><div><p class="font-mono text-[10px] font-semibold uppercase tracking-[.18em] text-[#f4511e]">Data transaksi</p><h2 id="booking-list-title" class="mt-1 font-['Outfit'] text-2xl font-bold">Daftar booking</h2></div><span class="font-mono text-xs text-[#756861]">{{ count($bookings) }} hasil</span></div>
            @if(count($bookings))<div class="overflow-x-auto border-y border-[#eadfd6] bg-white"><table class="w-full min-w-[980px] text-left text-sm"><caption class="sr-only">Daftar booking event</caption><thead class="border-b border-[#eadfd6] bg-[#fff0e9] text-[10px] uppercase tracking-[.14em] text-[#756861]"><tr><th class="px-5 py-3">Kode booking</th><th class="px-5 py-3">Pembeli</th><th class="px-5 py-3">Event</th><th class="px-5 py-3">Tiket</th><th class="px-5 py-3">Total</th><th class="px-5 py-3">Pembayaran</th><th class="px-5 py-3">Booking</th><th class="px-5 py-3">Waktu</th><th class="px-5 py-3"><span class="sr-only">Aksi</span></th></tr></thead><tbody class="divide-y divide-[#eadfd6]">@foreach($bookings as $item)<tr class="hover:bg-[#fff9f3]"><td class="px-5 py-4 font-mono text-xs font-semibold">{{ $item['code'] }}</td><td class="px-5 py-4"><p class="font-semibold">{{ $item['buyer'] }}</p><p class="mt-0.5 text-xs text-[#756861]">{{ $item['email'] }}</p></td><td class="px-5 py-4 text-[#756861]">{{ $item['event'] }}</td><td class="px-5 py-4">{{ $item['tickets'] }}</td><td class="px-5 py-4 font-semibold">{{ $item['total'] }}</td><td class="px-5 py-4"><span class="rounded-full {{ $item['payment'] === 'Paid' ? 'bg-[#edf3ec] text-[#287a54]' : 'bg-[#fbf3db] text-[#956400]' }} px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.08em]">{{ $item['payment'] }}</span></td><td class="px-5 py-4"><span class="rounded-full {{ $item['status'] === 'Cancelled' ? 'bg-[#fbe9e7] text-[#b33d38]' : ($item['status'] === 'Confirmed' ? 'bg-[#edf3ec] text-[#287a54]' : 'bg-[#fbf3db] text-[#956400]') }} px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.08em]">{{ $item['status'] }}</span></td><td class="px-5 py-4 whitespace-nowrap text-xs text-[#756861]">{{ $item['booked_at'] }}</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.bookings.show', $item['code']) }}" class="font-semibold text-[#a9361f] underline decoration-[#f8c1ae] underline-offset-4">Lihat</a></td></tr>@endforeach</tbody></table></div>@else<div class="border-y border-[#eadfd6] bg-white px-6 py-12 text-center"><p class="font-['Outfit'] text-xl font-bold">Booking tidak ditemukan</p><p class="mt-2 text-sm text-[#756861]">Coba ubah kata kunci atau filter pencarian.</p></div>@endif
        </section><nav class="mt-5 flex items-center justify-between text-sm text-[#756861]" aria-label="Pagination"><span>Menampilkan 1–{{ count($bookings) }} dari 128 booking</span><span class="border border-[#eadfd6] bg-white px-3 py-2 text-xs">Halaman 1</span></nav>
        <footer class="mt-10 border-t border-[#eadfd6] pt-5 text-xs text-[#9f8f87]">Admin Event Organizer <span class="mx-2">/</span> Booking <span class="mx-2">/</span> v0.1</footer>
    </div></main>
</div></body></html>
