<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $booking['code'] }} | Booking</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-[100dvh] bg-[#fff9f3] text-[#2c221e] antialiased"><div class="min-h-[100dvh]">@include('components.admin-sidebar')<main class="admin-shell-content min-w-0 lg:ml-[248px] lg:max-h-[100dvh] lg:overflow-y-auto"><div class="mx-auto max-w-[1180px] px-5 py-6 sm:px-7 lg:px-12 lg:py-9">
    <a href="{{ route('admin.bookings') }}" class="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[#a9361f] hover:text-[#762817]"><svg aria-hidden="true" viewBox="0 0 24 24" class="h-4 w-4 fill-none stroke-current" stroke-width="1.8"><path d="m15 5-7 7 7 7"/></svg>Kembali ke booking</a>
    @if(session('status'))<div class="mt-5 border border-[#b9d8c5] bg-[#edf3ec] px-4 py-3 text-sm text-[#287a54]" role="status">{{ session('status') }}</div>@endif
    <header class="mt-7 border-b border-[#eadfd6] pb-7"><div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="font-mono text-[11px] font-semibold uppercase tracking-[.18em] text-[#f4511e]">Booking / detail</p><h1 class="mt-2 font-['Outfit'] text-4xl font-extrabold tracking-[-.055em]">{{ $booking['code'] }}</h1><p class="mt-2 text-sm text-[#756861]">Dibuat {{ $booking['booked_at'] }}</p></div><div class="flex gap-2"><span class="rounded-full {{ $booking['payment'] === 'Paid' ? 'bg-[#edf3ec] text-[#287a54]' : 'bg-[#fbf3db] text-[#956400]' }} px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.08em]">{{ $booking['payment'] }}</span><span class="rounded-full {{ $booking['status'] === 'Confirmed' ? 'bg-[#edf3ec] text-[#287a54]' : 'bg-[#fbf3db] text-[#956400]' }} px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.08em]">{{ $booking['status'] }}</span></div></div></header>
    <section class="grid gap-8 py-8 lg:grid-cols-[minmax(0,1fr)_340px]" aria-label="Detail booking"><div class="space-y-8">
        <article class="border border-[#eadfd6] bg-white"><div class="border-b border-[#eadfd6] px-6 py-5"><p class="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#9f8f87]">Pembeli</p><h2 class="mt-1 font-['Outfit'] text-2xl font-bold">Informasi pembeli</h2></div><dl class="divide-y divide-[#eadfd6] px-6"><div class="flex flex-col gap-1 py-4 sm:flex-row sm:justify-between"><dt class="text-sm text-[#756861]">Nama</dt><dd class="text-sm font-semibold sm:text-right">{{ $booking['buyer'] }}</dd></div><div class="flex flex-col gap-1 py-4 sm:flex-row sm:justify-between"><dt class="text-sm text-[#756861]">Email</dt><dd class="text-sm sm:text-right">{{ $booking['email'] }}</dd></div><div class="flex flex-col gap-1 py-4 sm:flex-row sm:justify-between"><dt class="text-sm text-[#756861]">Telepon</dt><dd class="text-sm sm:text-right">{{ $booking['phone'] }}</dd></div></dl></article>
        <article class="border border-[#eadfd6] bg-white"><div class="border-b border-[#eadfd6] px-6 py-5"><p class="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#9f8f87]">Event dan tiket</p><h2 class="mt-1 font-['Outfit'] text-2xl font-bold">{{ $booking['event'] }}</h2><p class="mt-1 text-sm text-[#756861]">{{ $booking['event_date'] }}</p></div><div class="divide-y divide-[#eadfd6] px-6">@foreach($booking['tickets'] as $ticket)<div class="flex flex-col gap-2 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold">{{ $ticket['name'] }} × {{ $ticket['qty'] }}</p><p class="mt-1 font-mono text-xs text-[#756861]">{{ $ticket['code'] }}</p></div><p class="font-semibold">{{ $ticket['total'] }}</p></div>@endforeach</div></article>
        <article class="border border-[#eadfd6] bg-white"><div class="border-b border-[#eadfd6] px-6 py-5"><p class="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#9f8f87]">Aktivitas</p><h2 class="mt-1 font-['Outfit'] text-2xl font-bold">Riwayat booking</h2></div><ol class="divide-y divide-[#eadfd6] px-6"><li class="flex gap-4 py-4"><span class="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#287a54]"></span><div><p class="text-sm font-semibold">Booking dibuat</p><p class="mt-1 text-xs text-[#756861]">{{ $booking['booked_at'] }} · oleh pembeli</p></div></li><li class="flex gap-4 py-4"><span class="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#f4511e]"></span><div><p class="text-sm font-semibold">Pembayaran {{ strtolower($booking['payment']) }}</p><p class="mt-1 text-xs text-[#756861]">Reference: {{ $booking['reference'] }}</p></div></li></ol></article>
    </div><aside class="space-y-6 self-start"><section class="border border-[#eadfd6] bg-white"><div class="border-b border-[#eadfd6] bg-[#fff0e9] px-6 py-5"><p class="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#a9361f]">Nilai transaksi</p><p class="mt-2 text-xs leading-5 text-[#756861]">Data finansial hanya dapat dilihat admin event.</p></div><dl class="divide-y divide-[#eadfd6] px-6"><div class="flex items-center justify-between py-5"><dt class="text-sm text-[#756861]">Total</dt><dd class="font-['Outfit'] text-2xl font-bold">{{ $booking['total'] }}</dd></div><div class="flex items-center justify-between py-4"><dt class="text-sm text-[#756861]">Payment reference</dt><dd class="max-w-[150px] text-right font-mono text-xs">{{ $booking['reference'] }}</dd></div></dl></section>
        <section class="border border-[#eadfd6] bg-white px-6 py-5"><p class="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#9f8f87]">Aksi terbatas</p>@if($booking['can_cancel'])<details class="mt-4"><summary class="flex min-h-11 cursor-pointer list-none items-center justify-center rounded-[5px] border border-[#b33d38] px-4 text-sm font-bold text-[#b33d38]">Cancel booking</summary><form method="POST" action="{{ route('admin.bookings.cancel', $booking['code']) }}" class="mt-4 border-t border-[#eadfd6] pt-4">@csrf<label for="reason" class="text-sm font-semibold">Alasan wajib</label><textarea id="reason" name="reason" rows="4" required minlength="10" class="mt-2 w-full rounded-[5px] border border-[#eadfd6] px-3 py-2 text-sm focus:border-[#f4511e] focus:ring-0" placeholder="Contoh: pembayaran melewati batas waktu."></textarea><button type="submit" class="mt-3 min-h-11 w-full rounded-[5px] bg-[#b33d38] px-4 text-sm font-bold text-[#fff9f3]">Konfirmasi cancel</button></form></details>@else<div class="mt-4 bg-[#fff0e9] px-4 py-3 text-xs leading-5 text-[#756861]">Booking paid/confirmed bersifat read-only. Cancel diproses oleh Finance atau Super Admin.</div><button type="button" class="mt-3 min-h-11 w-full rounded-[5px] border border-[#f4511e] px-4 text-sm font-bold text-[#a9361f]">Ajukan koreksi</button>@endif<p class="mt-4 text-xs leading-5 text-[#9f8f87]">Setiap aksi sensitif meminta alasan dan dicatat ke audit log.</p></section>
        <section class="border border-[#eadfd6] bg-white px-6 py-5"><p class="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#9f8f87]">Audit log</p><p class="mt-2 text-sm font-semibold">Belum ada perubahan admin</p><p class="mt-1 text-xs leading-5 text-[#756861]">Riwayat keputusan dan alasan akan tampil di sini.</p></section></aside>
    </section><footer class="border-t border-[#eadfd6] pt-5 text-xs text-[#9f8f87]">Admin Event Organizer <span class="mx-2">/</span> Booking detail <span class="mx-2">/</span> v0.1</footer>
</div></main></div></body></html>
