<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ringkasan | Admin Event Organizer</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-[100dvh] bg-[#fff9f3] text-[#2c221e] antialiased">
<div class="min-h-[100dvh]">
    @include('components.admin-sidebar')
    <main class="admin-shell-content min-w-0 lg:ml-[248px] lg:max-h-[100dvh] lg:overflow-y-auto">
        <div class="mx-auto max-w-[1400px] px-5 py-6 sm:px-7 lg:px-12 lg:py-9">
            <header class="flex flex-col gap-5 border-b border-[#eadfd6] pb-7 sm:flex-row sm:items-end sm:justify-between">
                <div><p class="font-mono text-[11px] font-semibold uppercase tracking-[.18em] text-[#f4511e]">Selasa, 02 September 2026</p><h1 class="mt-2 font-['Outfit'] text-4xl font-extrabold tracking-[-.055em] sm:text-5xl">Ringkasan platform</h1><p class="mt-3 max-w-[65ch] text-sm leading-6 text-[#756861]">Pantau event, vendor, dan transaksi yang butuh perhatian hari ini.</p></div>
                <button class="inline-flex min-h-11 items-center justify-center gap-2 rounded-[5px] bg-[#f4511e] px-4 text-sm font-bold text-[#fff9f3] hover:bg-[#d94216] active:scale-[.98]">+ <span>Buat event</span></button>
            </header>
            <section class="grid gap-5 py-7 lg:grid-cols-[1.4fr_.8fr]" aria-label="Ringkasan metrik">
                <article class="border border-[#eadfd6] bg-white p-6 sm:p-7"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-[#756861]">Nilai booking bulan ini</p><p class="mt-3 font-['Outfit'] text-5xl font-extrabold tracking-[-.06em]">Rp184,6 jt</p></div><span class="rounded-full bg-[#edf3ec] px-3 py-1.5 text-xs font-bold text-[#287a54]">+18,4% vs Agustus</span></div><div class="mt-8 flex h-20 items-end gap-1.5" aria-label="Grafik nilai booking tujuh bulan terakhir"><i class="h-[34%] flex-1 rounded-t-sm bg-[#f8c1ae]"></i><i class="h-[48%] flex-1 rounded-t-sm bg-[#f8c1ae]"></i><i class="h-[42%] flex-1 rounded-t-sm bg-[#f8c1ae]"></i><i class="h-[63%] flex-1 rounded-t-sm bg-[#f8c1ae]"></i><i class="h-[58%] flex-1 rounded-t-sm bg-[#f8c1ae]"></i><i class="h-[76%] flex-1 rounded-t-sm bg-[#f8c1ae]"></i><i class="h-full flex-1 rounded-t-sm bg-[#f4511e]"></i></div><div class="mt-3 flex justify-between font-mono text-[10px] uppercase tracking-[.14em] text-[#9f8f87]"><span>Apr</span><span>Mei</span><span>Jun</span><span>Jul</span><span>Agt</span><span>Sep</span></div></article>
                <div class="divide-y divide-[#eadfd6] border-y border-[#eadfd6] bg-[#fff0e9]"><div class="flex items-center justify-between px-6 py-5"><div><p class="text-xs font-semibold uppercase tracking-[.12em] text-[#756861]">Event aktif</p><p class="mt-1 font-['Outfit'] text-3xl font-bold">28</p></div><span class="text-2xl text-[#a9361f]">▣</span></div><div class="flex items-center justify-between px-6 py-5"><div><p class="text-xs font-semibold uppercase tracking-[.12em] text-[#756861]">Menunggu approval</p><p class="mt-1 font-['Outfit'] text-3xl font-bold">06</p></div><span class="rounded-full bg-[#fbf3db] px-3 py-1 text-xs font-bold text-[#956400]">Perlu tinjau</span></div></div>
            </section>
            <section class="grid gap-8 xl:grid-cols-[1.4fr_.8fr]">
                <article id="bookings"><div class="mb-4 flex items-end justify-between gap-4"><div><p class="font-mono text-[10px] font-semibold uppercase tracking-[.18em] text-[#f4511e]">Aktivitas terbaru</p><h2 class="mt-1 font-['Outfit'] text-2xl font-bold">Booking terakhir</h2></div><a href="#bookings" class="text-sm font-bold text-[#a9361f] underline decoration-[#f8c1ae] underline-offset-4">Lihat semua</a></div><div class="overflow-x-auto border-y border-[#eadfd6] bg-white"><table class="w-full min-w-[610px] text-left text-sm"><caption class="sr-only">Daftar booking terakhir</caption><thead class="border-b border-[#eadfd6] bg-[#fff9f3] text-[10px] uppercase tracking-[.14em] text-[#756861]"><tr><th scope="col" class="px-5 py-3 font-semibold">Booking</th><th scope="col" class="px-5 py-3 font-semibold">Customer</th><th scope="col" class="px-5 py-3 font-semibold">Event</th><th scope="col" class="px-5 py-3 font-semibold">Nilai</th><th scope="col" class="px-5 py-3 font-semibold">Status</th></tr></thead><tbody class="divide-y divide-[#eadfd6]"><tr class="hover:bg-[#fff9f3]"><td class="px-5 py-4 font-mono text-xs font-semibold">BK-2609028</td><td class="px-5 py-4 font-medium">Nadya Prameswari</td><td class="px-5 py-4 text-[#756861]">Otaku Matsuri 2026</td><td class="px-5 py-4 font-semibold">Rp680.000</td><td class="px-5 py-4"><span class="rounded-full bg-[#edf3ec] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.08em] text-[#287a54]">Paid</span></td></tr><tr class="hover:bg-[#fff9f3]"><td class="px-5 py-4 font-mono text-xs font-semibold">BK-2609027</td><td class="px-5 py-4 font-medium">Bagas Wicaksono</td><td class="px-5 py-4 text-[#756861]">Comic Frontier Mini</td><td class="px-5 py-4 font-semibold">Rp245.000</td><td class="px-5 py-4"><span class="rounded-full bg-[#fbf3db] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.08em] text-[#956400]">Pending</span></td></tr></tbody></table></div></article>
                <aside id="vendors"><div class="mb-4 flex items-end justify-between gap-4"><div><p class="font-mono text-[10px] font-semibold uppercase tracking-[.18em] text-[#f4511e]">Antrian admin</p><h2 class="mt-1 font-['Outfit'] text-2xl font-bold">Butuh tinjauan</h2></div><span class="font-mono text-xs text-[#756861]">06 item</span></div><div class="divide-y divide-[#eadfd6] border-y border-[#eadfd6] bg-white"><a href="#vendors" class="flex items-start gap-4 px-5 py-5 hover:bg-[#fff9f3]"><span class="mt-1 text-lg text-[#956400]">!</span><span><b class="block text-sm">Neko Neko Studio</b><small class="mt-1 block text-xs leading-5 text-[#756861]">Pengajuan vendor · 2 jam lalu</small></span></a><a href="#events" class="flex items-start gap-4 px-5 py-5 hover:bg-[#fff9f3]"><span class="mt-1 text-lg text-[#f4511e]">□</span><span><b class="block text-sm">Sakura Night Market</b><small class="mt-1 block text-xs leading-5 text-[#756861]">Moderasi event · 5 jam lalu</small></span></a><a href="#categories" class="flex items-start gap-4 px-5 py-5 hover:bg-[#fff9f3]"><span class="mt-1 text-lg text-[#287a54]">✓</span><span><b class="block text-sm">Kategori baru menunggu</b><small class="mt-1 block text-xs leading-5 text-[#756861]">Moderasi kategori · kemarin</small></span></a></div></aside>
            </section>
            <footer class="mt-10 border-t border-[#eadfd6] pt-5 text-xs text-[#9f8f87]">Admin Event Organizer <span class="mx-2">/</span> Workspace platform <span class="mx-2">/</span> v0.1</footer>
        </div>
    </main>
</div>
</body>
</html>
