@csrf
@if($errors->any())
<div class="mb-6 border border-[#efb5b0] bg-[#fff0e9] px-4 py-3 text-sm text-[#b33d38]"><p class="font-semibold">Periksa kembali form.</p><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif
<div class="grid gap-6 sm:grid-cols-2">
    <div class="sm:col-span-2"><label for="title" class="text-sm font-semibold">Nama event</label><input id="title" name="title" value="{{ old('title', $event?->title) }}" required maxlength="150" class="field"></div>
    <div><label for="vendor_id" class="text-sm font-semibold">Vendor</label><select id="vendor_id" name="vendor_id" required class="field"><option value="">Pilih vendor</option>@foreach($vendors as $vendor)<option value="{{ $vendor->id }}" @selected(old('vendor_id', $event?->vendor_id) == $vendor->id)>{{ $vendor->organization_name }}</option>@endforeach</select></div>
    <div><label for="category_id" class="text-sm font-semibold">Kategori</label><select id="category_id" name="category_id" required class="field"><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $event?->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div><label for="event_date" class="text-sm font-semibold">Tanggal</label><input id="event_date" name="event_date" type="date" value="{{ old('event_date', $event?->event_date?->format('Y-m-d')) }}" required class="field"></div>
    <div><label for="status" class="text-sm font-semibold">Status</label><select id="status" name="status" required class="field">@foreach(['draft','published','cancelled','completed'] as $status)<option value="{{ $status }}" @selected(old('status', $event?->status ?? 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
    <div><label for="start_time" class="text-sm font-semibold">Waktu mulai</label><input id="start_time" name="start_time" type="time" value="{{ old('start_time', $event?->start_time?->format('H:i')) }}" required class="field"></div>
    <div><label for="end_time" class="text-sm font-semibold">Waktu selesai</label><input id="end_time" name="end_time" type="time" value="{{ old('end_time', $event?->end_time?->format('H:i')) }}" required class="field"></div>
    <div class="sm:col-span-2"><label for="venue_name" class="text-sm font-semibold">Nama lokasi</label><input id="venue_name" name="venue_name" value="{{ old('venue_name', $event?->venue_name) }}" required maxlength="150" class="field"></div>
    <div class="sm:col-span-2"><label for="venue_address" class="text-sm font-semibold">Alamat lokasi</label><textarea id="venue_address" name="venue_address" rows="2" required maxlength="500" class="field">{{ old('venue_address', $event?->venue_address) }}</textarea></div>
    <div class="sm:col-span-2"><label for="poster" class="text-sm font-semibold">Foto poster <span class="font-normal text-[#756861]">(JPG/PNG, maksimal 5 MB)</span></label><div class="mt-2 flex min-h-14 items-center rounded-[5px] border border-[#eadfd6] bg-[#fff9f3] px-3"><input id="poster" name="poster" type="file" accept=".jpg,.jpeg,.png,image/jpeg,image/png" {{ $event ? '' : 'required' }} class="sr-only"><label for="poster" class="inline-flex min-h-10 cursor-pointer items-center rounded-[5px] bg-[#a9361f]/70 px-4 text-sm font-semibold text-[#fff9f3] transition-colors hover:bg-[#a9361f]/85">Choose File</label><span id="poster-name" class="ml-3 truncate text-sm text-[#756861]">No file chosen</span></div>@if($event?->poster)<p class="mt-2 text-xs text-[#756861]">Poster saat ini: {{ basename($event->poster) }}. Kosongkan jika tidak ingin mengganti.</p>@endif</div>
    <div class="sm:col-span-2"><label for="description" class="text-sm font-semibold">Deskripsi</label><textarea id="description" name="description" rows="5" required maxlength="5000" class="field py-3">{{ old('description', $event?->description) }}</textarea></div>
</div>
<div class="mt-8 flex flex-col-reverse gap-3 border-t border-[#eadfd6] pt-6 sm:flex-row sm:justify-end"><a href="{{ route('admin.events') }}" class="inline-flex min-h-11 items-center justify-center rounded-[5px] border border-[#eadfd6] px-5 text-sm font-bold text-[#756861]">Batal</a><button type="submit" class="inline-flex min-h-11 items-center justify-center rounded-[5px] bg-[#f4511e] px-5 text-sm font-bold text-[#fff9f3]">{{ $submitLabel }}</button></div>
<style>.field{margin-top:.5rem;min-height:2.75rem;width:100%;border:1px solid #eadfd6;border-radius:5px;background:#fff9f3;padding:0 .75rem;font-size:.875rem}.field:focus{border-color:#f4511e;outline:2px solid #f8c1ae;outline-offset:1px}</style>
<script>document.getElementById('poster')?.addEventListener('change', function () { document.getElementById('poster-name').textContent = this.files[0]?.name ?? 'No file chosen'; });</script>
